/* Set-up */
CLEAR COLUMNS

/* Start output of report */
SPOOL q2_output.txt

/* Formatting of report */
TTITLE LEFT 'Q2: Fields which contain finds' SKIP 2
COLUMN FIELD_ID HEADING 'Field ID ' FORMAT 9
COLUMN OWNER HEADING 'Owner' FORMAT A15
COLUMN CROP HEADING 'Crop' FORMAT A15
COLUMN AREA HEADING ' Area (sq units)' FORMAT 0.99
COLUMN CLASS HEADING 'Class of Find(s)' FORMAT A17
SET UNDERLINE =
SET PAGESIZE 300
BREAK ON FIELD_ID ON OWNER ON CROP ON AREA SKIP 1

/* Start of query */
SELECT A.FIELD_ID, A.OWNER, C.NAME AS CROP, A.AREA, D.NAME AS CLASS
FROM GISTEACH.FIELDS A,GISTEACH.FINDS B,
GISTEACH.CROPS C,GISTEACH.CLASS D
WHERE A.CROP = C.CROP
AND B.TYPE = D.TYPE
AND B.XCOORD BETWEEN A.LOWX AND A.HIX
AND B.YCOORD BETWEEN A.LOWY AND A.HIY
ORDER BY A.FIELD_ID
/
/* End of query */
SPOOL OFF
/* End of output */
