/* Set up */
CLEAR COLUMNS

/* Start of output */
SPOOL q4_output.txt

/* Formatting of report */
TTITLE LEFT 'Finds in fields with above average length of growing season' SKIP 2
COLUMN FIND_ID HEADING 'Find ID ' FORMAT 9
COLUMN CLASS HEADING 'Class of Find(s)' FORMAT A17
COLUMN FIELD_NOTES HEADING 'Field Notes' FORMAT A20 WORD_WRAP
SET UNDERLINE =
SET PAGESIZE 300

/* Start of query */
SELECT A.FIND_ID, B.NAME AS CLASS, A.FIELD_NOTES
FROM GISTEACH.FINDS A,GISTEACH.CLASS B,
GISTEACH.FIELDS C, GISTEACH.CROPS D
WHERE A.TYPE = B.TYPE
AND C.CROP = D.CROP
AND A.XCOORD BETWEEN C.LOWX AND C.HIX
AND A.YCOORD BETWEEN C.LOWY AND C.HIY
AND (D.END_OF_SEASON - D.START_OF_SEASON) >
/* Subquery to get average season length */
(
  SELECT AVG(E.END_OF_SEASON - E.START_OF_SEASON)
FROM GISTEACH.CROPS E
)
ORDER BY A.FIND_ID
/
/* End of query */
SPOOL OFF
/*End of output */ 
